#!/usr/bin/node
var dgram = require('dgram');
var Logger = require('./logger');
var helpers = require('./helper');
process.stdin.setEncoding('utf8');

// UDP Total DataLimit of 1472 bytes
// var packetSize = 1472;
// if we use  4 bytes for our sequence, then we have 1468 bytes left
var Sender = function () {
    'use strict';
    // read from the input to get port number
      var input = process.argv;
    
    if (!input[2]) {
        // use preset for testing
       input = ['127.0.0.1', 56999];
    } else {
        input = process.argv[2].split(':');
    }
    
    this.logger = new Logger();
    this.window = 10;
    this.done = false;
    this.sequence = 0;
    this.queue = [];
    this.ack = {};
    this.timeout = 500;
    this.waiting = false;
    this.packetSize = 1472;
    this.highestConsqAck = 0;

    // parse the command line arguments for the assigned port
    this.host = input[0];
    this.port = input[1];

    // print to STDERR the specified error message
    this.logger.log(this.host + ':' + this.port);
    // this.listen(this);
    // this.logger.log(this.host + ':' + this.port);

    // bind a UDP socket to the specified port
    this.server = dgram.createSocket('udp4');
    this.server.bind();
    // this.bufferSize = 0;
};

// read the input stream from STDIn at once, to ensure maximum packet stuffing
Sender.prototype.listen = function (self) {
    "use strict";
    var bufferArr = [];
    process.stdin.on('readable', function () {
        var chunk = process.stdin.read();
        var buff;
        if (chunk) {
            buff = new Buffer(chunk);
            bufferArr.push(buff);
            self.bufferSize += buff.length;
        } else {
            var catbuff = Buffer.concat(bufferArr, 'utf8');
            this.processChunk(catbuff.toString());
    }

        // self.seqLength = self.buffersize;  // divide out the constant?? prob not worth it
        // self.seqLength = Math.ceil(self.bufferSize / self.dataLength);
        // bind a UDP socket to the specified port
        // this.server = dgram.createSocket('udp4');
        // this.server.bind();
    });
    // return bufferArr;
};

Sender.prototype.listenAck = function (self) {
    "use strict";
    // continue execution of the program, self should be moved
    if (self.waiting) {
        clearTimeout(self.timer);
        self.waiting = false;
        self.window *= 1.2;
        return true;
        // self.sendPackets();
    } else {
        return false;
        // self.sendPackets();
    }
};


Sender.prototype.updateRTT = function (d2, self) {
    "use strict";
    var d1 = self.sendTime;
    self.sendTime = false;
    var diff = ~~(d2.getTime() - d1.getTime());
    self.timeout = ~~(self.timeout * 0.8 + 0.2 * diff);
};

Sender.prototype.processChunk = function (chunk, length, self) {
    "use strict";
    var chunkSize = Buffer.byteLength(chunk, 'utf8');
    if (chunkSize <= length) {
        self.queue.push(chunk);
    } else if (chunkSize > length) {
        var stringToChunk;
        while (Buffer.byteLength(chunk, 'utf8') > length) {
            stringToChunk = self.stringToChunk(chunk);
            chunk = stringToChunk[1];
            self.queue.push(stringToChunk[0]);
        }
        if (chunk) {
            self.queue.push(chunk);
        }
    }
};


Sender.prototype.sendPackets = function (self) {
        "use strict";

        var start = helpers.seqToIndex(self.sequence);
        self.sendTime = new Date();
        var i = self.highestConsqAck;

        for (start = 0; i < self.window ; i += 1) {
        
        if (!self.queue[i]) {
            self.logger.log("!this.queue[i]" + i);
            
        } else if (!self.ack[i]) {
            self.ack[i] = false;
            // self.window += 3;
            // hasnt been sent before, send it for hte first time 
        } else {  // if self.ack[i]==fale
            // probable duplicate but could be a time out
            if ((self.highestConsqAck -= 1) === i) { 
                self.highestConsqAck = i;
            }
            // self.server.send(buffer, 0, buffer.length, self.port, self.host);
            self.logger.log("sending this.queue[--i]" + i);
            self.sendData(self.queue[i], false, false, self);
        }
            
    }// else { 
        //this.ackStatus[i + 1] = {acked: false};
            // will resend if it has timed out 
            // this.resendData(i);
        //}
};

Sender.prototype.waitForAck = function (self) {
    "use strict";
    // set boolean so it will run once and only once
    self.waiting = true;
    self.timer = setTimeout(function () {
        if (self.waiting) {
            self.waiting = false;
            // if  self.window > 1) self.window--;
            // self.rebroadcast(self);
        }
    }, this.timeout);
};

Sender.prototype.sendData = function (data, resending, seq, self) {
    "use strict";
    var dataBuffer = new Buffer(data.size);
    if (!resending) {
        self.sequence += dataBuffer.length;
        seq = self.sequence;
    } else 
    // if no sequence number given, its a new packet
    if (seq) {
       // self.ack[helpers.seqToIndex(seq)].seq = seq;
    }

    var sequence = helpers.intBufferToIndex(seq, self.seqLength);
    
    var buffer = Buffer.concat([sequence, data]);

    self.logger.log('[send data] ' + self.sequence + ' (' + data.length + ')');

    self.ack[sequence] = {acked: false};    // data is actually sent here
    self.server.send(buffer, 0, buffer.length, self.port, self.host);
};


Sender.prototype.rebroadcast = function(key, self) {
    "use strict";   
    // iterate over the ack array for outstanding packets
    if (self.ack) { 
    Object.keys(self.ack).forEach(function(key) {
        // if we find one resend it 
        if (!self.ack[key].acked) {
            // the data is in the queue which indexed by the sequence number
            self.sendData(self.queue[key - 1], true, self.ack[key].seq);
            //this.window--; 
        }
    });
    }
};


// Returns a touple of [Chunk, Rest of string]
Sender.prototype.stringToChunk = function (str) {
    "use strict";
    var chunk = '';
    var char = str.charAt(0);
    while (Buffer.byteLength(chunk, 'utf8') < 1468) {
        char = str.charAt(0);
        if (Buffer.byteLength(chunk + char, 'utf8') <= 1468) {
            chunk += char;
            str = str.slice(1);
        } else {
            break;
        }
    }
    return [chunk, str];
};

// Returns a touple of [Chunk, Rest of string]
Sender.prototype.checkAnyOutstanding = function (self) {
    "use strict";     
    var lastIndex = self.bufferSize;
    // // check for time outs and update the acks accordingly
    // helper function parses the array and decodes the dynamic sequence number length
    // var packetIndex = helpers.seqArrayIndexFromMessageBuffer(msg);
    var i;
    for (i = 0; i > (lastIndex); i += 1) {
        if (self.ack[i] || self.ack[i].acked) {
            // done = false;
            // self.logger.log("MISSING THIS PACKET : " + i);
            // break;
            // done = true;
        } else {
            return false;        }   
    }
    return true;
};

const sender = new Sender();

var serverLoop = false;

sender.server.on('listening', function () {
    "use strict";
    // sender.logger.log('entering listening');
    // sender.listen(sender);
    // sender.logger.log('exit listening');
    sender.listen(sender);
    serverLoop = true;
}); //.bind(sender); 


while (serverLoop) { 
    sender.logger.log('entering serverloop');
    sender.sendPackets(sender);
    sender.waitForAck(sender);
    serverLoop = sender.checkAnyOutstanding(sender);
}

sender.server.on('message', function (msg, rinfo) {
        "use strict";
        // fix to the special EOF value
        
        if (msg.buf.length === 1) {
            sender.logger.log('[completed]');
            process.exit(rinfo);
        }
        sender.window += 3;
        sender.listenAck(sender);
        var packetIndex = helpers.seqArrayIndexFromMessageBuffer(msg);
        sender.ack[packetIndex].acked = true;
});

// Logger.log("hi");


